### ISSUE TITLE
support for global

### ISSUE THREAD

**Issue by dpocock** [andrewrk/browserify-lite#4]
If a module refers to ```global```, browserify wraps the module:

      32:[function(require,module,exports){
         (function (global){
      ... module source ...
      }).call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})

so that references to ```global``` will work.

As a workaround, it is possible to patch browserify-lite output with sed to correct references to ```global``` and change them to ```window``` but could this be done in browserify-lite somehow?

**Comment by andrewrk** [comment]
Why not just add `global` to the parameter list like this?

```js
32:[function(require,module,exports, global){
   ... module source ...
```

**Comment by dpocock** [comment]
With browserify, ```global``` is not always ```window``` - it is also meant to be possible to use the browserified JavaScript in Node.  But for browserify-lite, I think that hardcoding it to window as you propose is fine.
