### ISSUE TITLE
support for standalone option

### ISSUE THREAD

**Issue by dpocock** [andrewrk/browserify-lite#5]
The ```--standalone``` option is used in the ```gulpfile.js``` of JsSIP

It is described here:

https://github.com/substack/browserify-handbook#standalone

Basically, it puts some object (in this case the JsSIP object) into ```window``` if it is running in a browser.

It is fairly easy to use ```sed``` on the output from browserify-lite to survive without this but it would be nice to support it if possible.

**Comment by andrewrk** [comment]
Alright give that a try and see what you think.
