### ISSUE TITLE
require('a' + 'b') not found

### ISSUE THREAD

**Issue by emersion** [andrewrk/browserify-lite#9]
In `readable-stream`:
```js
var Stream;
(function (){try{
  Stream = require('st' + 'ream');
}catch(_){}finally{
  if (!Stream)
    Stream = require('events').EventEmitter;
}}())
```

Got:
```
Error: module st in node_modules/readable-stream not found
```

Expected: do not detect this `require()`.

**Comment by andrewrk** [comment]
This will never be fixed in this module. It's one of the limitations.

**Comment by emersion** [comment]
Don't you think it _can_ be fixed here: https://github.com/andrewrk/browserify-lite/blob/master/index.js#L230 ?

```js
    } else if (state === STATE_WANT_RPAREN && token === ')') {
      state = STATE_WANT_REQUIRE;
      requiresList.push(requireName);
    } else if (state === STATE_WANT_RPAREN && token !== ')') { // String followed by non-RPAREN
      state = STATE_WANT_REQUIRE;
    }
```

**Comment by andrewrk** [comment]
Can you justify the use case?

**Comment by emersion** [comment]
A correct `require()` statement contains exactly: require, (, a string, ). Here in `readable-stream` there is an _invalid_ one, by invalid I mean a statement that works in Node but not in Browserify. Here, they want to check if the native `stream` module is available. That's why it's surrounded with `try` / `catch`. It's a common practice, even if it's not the best.

`browserify` just ignores these _invalid_ `require()`. But `browserify-lite` parses `require('st' + 'ream')` as `require('st')` and doesn't find the module `st`.

To fix that, you can just add another condition in the parser code: if we are waiting for a right parenthesis and there is no one, ignore the `require()` call.

**Comment by andrewrk** [comment]
OK, I agree that parsing `require('st' + 'ream')` as `require('st')` is a bug that should be fixed.
